//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Hpc.Excel.ExcelService {

    using System.Runtime.InteropServices;

	/// <summary>
	///   <para>
	/// Represents the Excel service
	/// </para>
	/// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExcelService.IExcelService")]
    public interface IExcelService {
        
		/// <summary>
		///   <para>
		/// Calculate the request
		/// </para>
		/// </summary>
		/// <param name="request">
		///   <para>Indicates the request</para>
		/// </param>
		/// <returns />
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExcelService/Calculate", ReplyAction="http://tempuri.org/IExcelService/CalculateResponse")]
        Microsoft.Hpc.Excel.ExcelService.CalculateResponse Calculate(Microsoft.Hpc.Excel.ExcelService.CalculateRequest request);
        
		/// <summary>
		///   <para>
		/// Begin async calculate the request
		/// </para>
		/// </summary>
		/// <param name="request">
		///   <para>Indicates the request</para>
		/// </param>
		/// <param name="callback">
		///   <para>Indicates the callback method</para>
		/// </param>
		/// <param name="asyncState">
		///   <para>Indicate the callback state</para>
		/// </param>
		/// <returns />
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IExcelService/Calculate", ReplyAction="http://tempuri.org/IExcelService/CalculateResponse")]
        System.IAsyncResult BeginCalculate(Microsoft.Hpc.Excel.ExcelService.CalculateRequest request, System.AsyncCallback callback, object asyncState);
        
		/// <summary>
		///   <para>
		/// End async calculate the request
		/// </para>
		/// </summary>
		/// <param name="result" />
		/// <returns />
        Microsoft.Hpc.Excel.ExcelService.CalculateResponse EndCalculate(System.IAsyncResult result);
    }
    
	/// <summary>
	///   <para>
	/// Represents the calculate request
	/// </para>
	/// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Calculate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculateRequest {
        
		/// <summary>
		///   <para>
		/// Indicates the macro name
		/// </para>
		/// </summary>
		/// <returns>
		///   <para />
		/// </returns>
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string macroName;
        
		/// <summary>
		///   <para>
		/// Indicates the inputs
		/// </para>
		/// </summary>
		/// <returns>
		///   <para />
		/// </returns>
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] inputs;
        
		/// <summary>
		///   <para>
		/// Indicates the last saved date
		/// </para>
		/// </summary>
		/// <returns>
		///   <para />
		/// </returns>
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<System.DateTime> lastSaveDate;
        
		/// <summary>
		///   <para>
		/// Constructor of the calculate request
		/// </para>
		/// </summary>
        public CalculateRequest() {
        }
        
		/// <summary>
		///   <para>
		/// Constructor of the calculate request
		/// </para>
		/// </summary>
		/// <param name="macroName">
		///   <para>Indicates the macro name</para>
		/// </param>
		/// <param name="inputs">
		///   <para>Indicates the inputs</para>
		/// </param>
		/// <param name="lastSaveDate">
		///   <para>Indicates the last saved date</para>
		/// </param>
        public CalculateRequest(string macroName, byte[] inputs, System.Nullable<System.DateTime> lastSaveDate) {
            this.macroName = macroName;
            this.inputs = inputs;
            this.lastSaveDate = lastSaveDate;
        }
    }
    
	/// <summary>
	///   <para>
	/// Represents the calculate response
	/// </para>
	/// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculateResponse {
        
		/// <summary>
		///   <para>
		/// Indicates the calculate result
		/// </para>
		/// </summary>
		/// <returns>
		///   <para />
		/// </returns>
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] CalculateResult;
        
		/// <summary>
		///   <para>
		/// Constructor of the calculate response
		/// </para>
		/// </summary>
        public CalculateResponse() {
        }
        
		/// <summary>
		///   <para>
		/// Constructor of the calculate response
		/// </para>
		/// </summary>
		/// <param name="CalculateResult">
		///   <para>Indicates the calculate result</para>
		/// </param>
        public CalculateResponse(byte[] CalculateResult) {
            this.CalculateResult = CalculateResult;
        }
    }
    
	/// <summary>
	///   <para>
	/// The interface for Excel service channel
	/// </para>
	/// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IExcelServiceChannel : Microsoft.Hpc.Excel.ExcelService.IExcelService, System.ServiceModel.IClientChannel {
    }
    
	/// <summary>
	///   <para>
	/// Represents the calculate completed event args
	/// </para>
	/// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CalculateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
		/// <summary>
		///   <para>
		/// Constructor of the calculate completed event args
		/// </para>
		/// </summary>
		/// <param name="results">
		///   <para>Indicates the results</para>
		/// </param>
		/// <param name="exception">
		///   <para>Indicates the exception</para>
		/// </param>
		/// <param name="cancelled">
		///   <para>Indicates whether it is cancelled</para>
		/// </param>
		/// <param name="userState">
		///   <para>Indicates the user state</para>
		/// </param>
        public CalculateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
		/// <summary>
		///   <para>
		/// Gets the calculate result
		/// </para>
		/// </summary>
		/// <value>
		///   <para />
		/// </value>
        public Microsoft.Hpc.Excel.ExcelService.CalculateResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Microsoft.Hpc.Excel.ExcelService.CalculateResponse)(this.results[0]));
            }
        }
    }
    
}
