//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Hpc.Scheduler.Session.Internal.BrokerLauncher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class BrokerLauncherSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BrokerLauncherSettings defaultInstance = ((BrokerLauncherSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BrokerLauncherSettings())));
        
        public static BrokerLauncherSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxConcurrentSession {
            get {
                return ((int)(this["MaxConcurrentSession"]));
            }
            set {
                this["MaxConcurrentSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BrokerPoolSize {
            get {
                return ((int)(this["BrokerPoolSize"]));
            }
            set {
                this["BrokerPoolSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SessionAddress {
            get {
                return ((string)(this["SessionAddress"]));
            }
            set {
                this["SessionAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\services\\registration")]
        public string CCP_SERVICEREGISTRATION_PATH {
            get {
                return ((string)(this["CCP_SERVICEREGISTRATION_PATH"]));
            }
            set {
                this["CCP_SERVICEREGISTRATION_PATH"] = value;
            }
        }
    }
}
