//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Telepathy.Internal.SessionLauncher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class SessionLauncherSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SessionLauncherSettings defaultInstance = ((SessionLauncherSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SessionLauncherSettings())));
        
        public static SessionLauncherSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableDataService {
            get {
                return ((bool)(this["EnableDataService"]));
            }
            set {
                this["EnableDataService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceRegistrationPath {
            get {
                return ((string)(this["ServiceRegistrationPath"]));
            }
            set {
                this["ServiceRegistrationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServiceRegistrationStoreFacadeFolder {
            get {
                return ((string)(this["ServiceRegistrationStoreFacadeFolder"]));
            }
            set {
                this["ServiceRegistrationStoreFacadeFolder"] = value;
            }
        }
    }
}
