//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Telepathy.Internal.SessionLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Telepathy.Internal.SessionLauncher.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DurableSession is not supported when the scheduler is in Azure..
        /// </summary>
        internal static string Azure_NotSupportDurableSession {
            get {
                return ResourceManager.GetString("Azure_NotSupportDurableSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inprocess broker is not supported when the scheduler is in Azure..
        /// </summary>
        internal static string Azure_NotSupportInprocessBroker {
            get {
                return ResourceManager.GetString("Azure_NotSupportInprocessBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enumerate cluster information..
        /// </summary>
        internal static string BrokerNodesManager_CannotEnumerateInformation {
            get {
                return ResourceManager.GetString("BrokerNodesManager_CannotEnumerateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to the scheduler..
        /// </summary>
        internal static string CannotConnectToScheduler {
            get {
                return ResourceManager.GetString("CannotConnectToScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized user: {0}.
        /// </summary>
        internal static string DataService_UnauthorizedUser {
            get {
                return ResourceManager.GetString("DataService_UnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified task id {0} is not valid. Check your task id and try again..
        /// </summary>
        internal static string DiagService_InvalidTaskId {
            get {
                return ResourceManager.GetString("DiagService_InvalidTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enumerate resource group..
        /// </summary>
        internal static string ResourceGroupInfo_CannotEnumerateResourceGroup {
            get {
                return ResourceManager.GetString("ResourceGroupInfo_CannotEnumerateResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get network name for resource group - {0}..
        /// </summary>
        internal static string ResourceGroupInfo_CannotGetNetworkName {
            get {
                return ResourceManager.GetString("ResourceGroupInfo_CannotGetNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open resource - {0}..
        /// </summary>
        internal static string ResourceGroupInfo_CannotOpenResource {
            get {
                return ResourceManager.GetString("ResourceGroupInfo_CannotOpenResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open resource group - {0}..
        /// </summary>
        internal static string ResourceGroupInfo_CannotOpenResourceGroup {
            get {
                return ResourceManager.GetString("ResourceGroupInfo_CannotOpenResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow property name..
        /// </summary>
        internal static string SchedulerDelegation_UnknowPropertyName {
            get {
                return ResourceManager.GetString("SchedulerDelegation_UnknowPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be alpha, numeric or punctuation.
        /// </summary>
        internal static string SessionLauncher_ArgumentMustBeAlphaNumeric {
            get {
                return ResourceManager.GetString("SessionLauncher_ArgumentMustBeAlphaNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not logon user. Please check username/password..
        /// </summary>
        internal static string SessionLauncher_CannotLogon {
            get {
                return ResourceManager.GetString("SessionLauncher_CannotLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client version {0} does not match the server version {1}. Please consider to update the client..
        /// </summary>
        internal static string SessionLauncher_ClientServerVersionMismatch {
            get {
                return ResourceManager.GetString("SessionLauncher_ClientServerVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The config file is invalid: {0}..
        /// </summary>
        internal static string SessionLauncher_ConfigFileInvalid {
            get {
                return ResourceManager.GetString("SessionLauncher_ConfigFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating task failed, Exception: {0}..
        /// </summary>
        internal static string SessionLauncher_CreateJobTasksFailure {
            get {
                return ResourceManager.GetString("SessionLauncher_CreateJobTasksFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndpointPrefix: {0}, endpoint prefix is not supported, please pass in &quot;net.tcp://&quot; or &quot;https://&quot;..
        /// </summary>
        internal static string SessionLauncher_EndpointNotSupported {
            get {
                return ResourceManager.GetString("SessionLauncher_EndpointNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get SSDL for broker node {0}. Inner exception: {1}.
        /// </summary>
        internal static string SessionLauncher_FailedToGetBrokerNodeSSDL {
            get {
                return ResourceManager.GetString("SessionLauncher_FailedToGetBrokerNodeSSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the scheduler for job monitor..
        /// </summary>
        internal static string SessionLauncher_FailToConnectToScheduler {
            get {
                return ResourceManager.GetString("SessionLauncher_FailToConnectToScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create broker nodes manager..
        /// </summary>
        internal static string SessionLauncher_FailToCreateBrokerManager {
            get {
                return ResourceManager.GetString("SessionLauncher_FailToCreateBrokerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create job: {0}..
        /// </summary>
        internal static string SessionLauncher_FailToCreateJob {
            get {
                return ResourceManager.GetString("SessionLauncher_FailToCreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enumerate service versions.
        /// </summary>
        internal static string SessionLauncher_FailToEnumerateServicVersions {
            get {
                return ResourceManager.GetString("SessionLauncher_FailToEnumerateServicVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get cluster property: {0}..
        /// </summary>
        internal static string SessionLauncher_FailToGetClusterProperty {
            get {
                return ResourceManager.GetString("SessionLauncher_FailToGetClusterProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get job property: {0}..
        /// </summary>
        internal static string SessionLauncher_FailToGetJobProperty {
            get {
                return ResourceManager.GetString("SessionLauncher_FailToGetJobProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open job: {0}..
        /// </summary>
        internal static string SessionLauncher_FailToOpenJob {
            get {
                return ResourceManager.GetString("SessionLauncher_FailToOpenJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit job: {0}..
        /// </summary>
        internal static string SessionLauncher_FailToSubmitJob {
            get {
                return ResourceManager.GetString("SessionLauncher_FailToSubmitJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password is necessary..
        /// </summary>
        internal static string SessionLauncher_NeedUserNameAndPassword {
            get {
                return ResourceManager.GetString("SessionLauncher_NeedUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session launcher does not connect to the scheduler..
        /// </summary>
        internal static string SessionLauncher_NoConnectionToScheduler {
            get {
                return ResourceManager.GetString("SessionLauncher_NoConnectionToScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service registration directories are specified in CCP_SERVICEREGISTRATION_PATH.
        /// </summary>
        internal static string SessionLauncher_NoServiceRegistrationDirs {
            get {
                return ResourceManager.GetString("SessionLauncher_NoServiceRegistrationDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheduler raises exception: {0}..
        /// </summary>
        internal static string SessionLauncher_SchedulerException {
            get {
                return ResourceManager.GetString("SessionLauncher_SchedulerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found. Please make sure service {0} is deployed on the cluster..
        /// </summary>
        internal static string SessionLauncher_ServiceNotFound {
            get {
                return ResourceManager.GetString("SessionLauncher_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service version not found. Please make sure service {0}_{1} is deployed on the cluster..
        /// </summary>
        internal static string SessionLauncher_ServiceVersionNotFound {
            get {
                return ResourceManager.GetString("SessionLauncher_ServiceVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: session {0} cannot be attached to because the session has already finished..
        /// </summary>
        internal static string SessionLauncher_ValidateJobFailed_AlreadyFinished {
            get {
                return ResourceManager.GetString("SessionLauncher_ValidateJobFailed_AlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: session {0} cannot be attached to when the service job is canceled..
        /// </summary>
        internal static string SessionLauncher_ValidateJobFailed_JobCanceled {
            get {
                return ResourceManager.GetString("SessionLauncher_ValidateJobFailed_JobCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: session {0} is an interactive session. It can only be attached to when its service job is queued or running..
        /// </summary>
        internal static string SessionLauncher_ValidateJobFailed_NotDurableSession {
            get {
                return ResourceManager.GetString("SessionLauncher_ValidateJobFailed_NotDurableSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: job {0} is not a service job..
        /// </summary>
        internal static string SessionLauncher_ValidateJobFailed_NotServiceJob {
            get {
                return ResourceManager.GetString("SessionLauncher_ValidateJobFailed_NotServiceJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected return value from ClusterEnum - {0}..
        /// </summary>
        internal static string UnexpectedReturnValue {
            get {
                return ResourceManager.GetString("UnexpectedReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured: {0}..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
