//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient
{
    using System;
    using System.Runtime.Serialization;
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqData", Namespace="http://schemas.datacontract.org/2004/07/TestService")]
    public partial class ReqData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CCP_TASKINSTANCEIDField;
        
        private System.DateTime commonDataAccessStartTimeField;
        
        private System.DateTime commonDataAccessStopTimeField;
        
        private long commonDataSizeField;
        
        private System.DateTime requestEndTimeField;
        
        private System.DateTime requestStartTimeField;

        private System.DateTime sendStartField;
        
        private byte[] responseDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCP_TASKINSTANCEID
        {
            get
            {
                return this.CCP_TASKINSTANCEIDField;
            }
            set
            {
                this.CCP_TASKINSTANCEIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime commonDataAccessStartTime
        {
            get
            {
                return this.commonDataAccessStartTimeField;
            }
            set
            {
                this.commonDataAccessStartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime commonDataAccessStopTime
        {
            get
            {
                return this.commonDataAccessStopTimeField;
            }
            set
            {
                this.commonDataAccessStopTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long commonDataSize
        {
            get
            {
                return this.commonDataSizeField;
            }
            set
            {
                this.commonDataSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime requestEndTime
        {
            get
            {
                return this.requestEndTimeField;
            }
            set
            {
                this.requestEndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime requestStartTime
        {
            get
            {
                return this.requestStartTimeField;
            }
            set
            {
                this.requestStartTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime sendStart
        {
            get
            {
                return this.sendStartField;
            }
            set
            {
                this.sendStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] responseData
        {
            get
            {
                return this.responseDataField;
            }
            set
            {
                this.responseDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestClient.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComputeWithInputData", ReplyAction="http://tempuri.org/IService1/ComputeWithInputDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentException), Action="http://tempuri.org/IService1/ComputeWithInputDataArgumentExceptionFault", Name="ArgumentException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        TestClient.ComputeWithInputDataResponse ComputeWithInputData(TestClient.ComputeWithInputDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ComputeWithInputData", ReplyAction="http://tempuri.org/IService1/ComputeWithInputDataResponse")]
        System.IAsyncResult BeginComputeWithInputData(TestClient.ComputeWithInputDataRequest request, System.AsyncCallback callback, object asyncState);
        
        TestClient.ComputeWithInputDataResponse EndComputeWithInputData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComputeWithInputDataPath", ReplyAction="http://tempuri.org/IService1/ComputeWithInputDataPathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentException), Action="http://tempuri.org/IService1/ComputeWithInputDataPathArgumentExceptionFault", Name="ArgumentException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        TestClient.ComputeWithInputDataPathResponse ComputeWithInputDataPath(TestClient.ComputeWithInputDataPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ComputeWithInputDataPath", ReplyAction="http://tempuri.org/IService1/ComputeWithInputDataPathResponse")]
        System.IAsyncResult BeginComputeWithInputDataPath(TestClient.ComputeWithInputDataPathRequest request, System.AsyncCallback callback, object asyncState);
        
        TestClient.ComputeWithInputDataPathResponse EndComputeWithInputDataPath(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComputeWithInputData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ComputeWithInputDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int millisec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] input_data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string commonData_dataClientId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public long responseSize;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public DateTime sendStart;
        
        public ComputeWithInputDataRequest()
        {
        }
        
        public ComputeWithInputDataRequest(int millisec, byte[] input_data, string commonData_dataClientId, long responseSize, DateTime sendStart)
        {
            this.millisec = millisec;
            this.input_data = input_data;
            this.commonData_dataClientId = commonData_dataClientId;
            this.responseSize = responseSize;
            this.sendStart = sendStart;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComputeWithInputDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ComputeWithInputDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestClient.ReqData ComputeWithInputDataResult;
        
        public ComputeWithInputDataResponse()
        {
        }
        
        public ComputeWithInputDataResponse(TestClient.ReqData ComputeWithInputDataResult)
        {
            this.ComputeWithInputDataResult = ComputeWithInputDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComputeWithInputDataPath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ComputeWithInputDataPathRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int millisec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string input_data_path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string common_data_path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public long responseSize;
        
        public ComputeWithInputDataPathRequest()
        {
        }
        
        public ComputeWithInputDataPathRequest(int millisec, string input_data_path, string common_data_path, long responseSize)
        {
            this.millisec = millisec;
            this.input_data_path = input_data_path;
            this.common_data_path = common_data_path;
            this.responseSize = responseSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComputeWithInputDataPathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ComputeWithInputDataPathResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestClient.ReqData ComputeWithInputDataPathResult;
        
        public ComputeWithInputDataPathResponse()
        {
        }
        
        public ComputeWithInputDataPathResponse(TestClient.ReqData ComputeWithInputDataPathResult)
        {
            this.ComputeWithInputDataPathResult = ComputeWithInputDataPathResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IService1Channel : TestClient.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TestClient.IService1>, TestClient.IService1
    {
        
        public Service1Client()
        {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TestClient.ComputeWithInputDataResponse ComputeWithInputData(TestClient.ComputeWithInputDataRequest request)
        {
            return base.Channel.ComputeWithInputData(request);
        }
        
        public System.IAsyncResult BeginComputeWithInputData(TestClient.ComputeWithInputDataRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginComputeWithInputData(request, callback, asyncState);
        }
        
        public TestClient.ComputeWithInputDataResponse EndComputeWithInputData(System.IAsyncResult result)
        {
            return base.Channel.EndComputeWithInputData(result);
        }
        
        public TestClient.ComputeWithInputDataPathResponse ComputeWithInputDataPath(TestClient.ComputeWithInputDataPathRequest request)
        {
            return base.Channel.ComputeWithInputDataPath(request);
        }
        
        public System.IAsyncResult BeginComputeWithInputDataPath(TestClient.ComputeWithInputDataPathRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginComputeWithInputDataPath(request, callback, asyncState);
        }
        
        public TestClient.ComputeWithInputDataPathResponse EndComputeWithInputDataPath(System.IAsyncResult result)
        {
            return base.Channel.EndComputeWithInputDataPath(result);
        }
    }
}
