//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Hpc.CcpServiceHosting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Hpc.CcpServiceHosting.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Cannot find the assembly file: {0}. Redeploy service..
        /// </summary>
        internal static string AssemblyFileCantFind {
            get {
                return ResourceManager.GetString("AssemblyFileCantFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Missing service assmebly file name in service registration file {0}. Service cannot be activated. Add the &quot;assembly&quot; attribute to &quot;service&quot; element. The value of the &quot;assembly&quot; attribute should be the full path of the service assembly..
        /// </summary>
        internal static string AssemblyFileNotRegistered {
            get {
                return ResourceManager.GetString("AssemblyFileNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Environment variable CCP_BROKERNODE is undefined.
        /// </summary>
        internal static string BrokerAddrCantBeNull {
            get {
                return ResourceManager.GetString("BrokerAddrCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Environment variable CCP_CHILDJOBID is undefined.
        /// </summary>
        internal static string CantFindBrokerJobId {
            get {
                return ResourceManager.GetString("CantFindBrokerJobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Environment variable CCP_HOME is undefined.
        /// </summary>
        internal static string CantFindCcpHome {
            get {
                return ResourceManager.GetString("CantFindCcpHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Environment variable CCP_JOBID is undefined.
        /// </summary>
        internal static string CantFindJobId {
            get {
                return ResourceManager.GetString("CantFindJobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Environment variable CCP_NUMCPUS is undefined.
        /// </summary>
        internal static string CantFindProcNum {
            get {
                return ResourceManager.GetString("CantFindProcNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Cannot find the service contract {0} in the assembly {1}. Check the service registration file..
        /// </summary>
        internal static string CantFindServiceContract {
            get {
                return ResourceManager.GetString("CantFindServiceContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Cannot find the service registration file: {0}. Service cannot be activated. Redeploy the service..
        /// </summary>
        internal static string CantFindServiceRegistrationFile {
            get {
                return ResourceManager.GetString("CantFindServiceRegistrationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Cannot find the service registration file in the following directory(s): {0} Service cannot be activated. Redeploy the service..
        /// </summary>
        internal static string CantFindServiceRegistrationFileUnderFolders {
            get {
                return ResourceManager.GetString("CantFindServiceRegistrationFileUnderFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Cannot find the service type {0} in the assembly {1}. Check the service registration file..
        /// </summary>
        internal static string CantFindServiceType {
            get {
                return ResourceManager.GetString("CantFindServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Environment variable CCP_TASKSYSTEMID is undefined.
        /// </summary>
        internal static string CantFindTaskId {
            get {
                return ResourceManager.GetString("CantFindTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Bootstrap]: Error when reading the standard error from the 32 bit service host..
        /// </summary>
        internal static string ErrorReadingBootstrapStderr {
            get {
                return ResourceManager.GetString("ErrorReadingBootstrapStderr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Bootstrap]: Error when reading the standard output from the 32 bit service host..
        /// </summary>
        internal static string ErrorReadingBootstrapStdout {
            get {
                return ResourceManager.GetString("ErrorReadingBootstrapStdout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GetBrokerEprThreadMain]: Exception occurred when trying to read the broker EPR from service job {0}: {1}.
        /// </summary>
        internal static string ExceptionGetBrokerEpr {
            get {
                return ResourceManager.GetString("ExceptionGetBrokerEpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Exception in reading the service registration file {0}: {1}.
        /// </summary>
        internal static string ExceptionInReadingRegistrationFile {
            get {
                return ResourceManager.GetString("ExceptionInReadingRegistrationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Failed to start the service. .
        /// </summary>
        internal static string FailedInStartingService {
            get {
                return ResourceManager.GetString("FailedInStartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Failed to delete the temp configuration file: {0}.
        /// </summary>
        internal static string FailedToDeleteTempConfigFile {
            get {
                return ResourceManager.GetString("FailedToDeleteTempConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize service.
        /// </summary>
        internal static string FailedToInitializeServiceHost {
            get {
                return ResourceManager.GetString("FailedToInitializeServiceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter format cannot be null..
        /// </summary>
        internal static string FormatCannotBeNull {
            get {
                return ResourceManager.GetString("FormatCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Failed to get CPU architecture setting in service registration file, using default value: X64..
        /// </summary>
        internal static string GetArchFailed {
            get {
                return ResourceManager.GetString("GetArchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GetBrokerEprThreadMain]: Timeout in getting the broker EPR from the service job after 20 seconds. To determin the cause, see the output of broker job Id = {0}..
        /// </summary>
        internal static string GetBrokerEprTimeOut {
            get {
                return ResourceManager.GetString("GetBrokerEprTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find registry key of headnode.
        /// </summary>
        internal static string RegisteredHeadNodeIsMissing {
            get {
                return ResourceManager.GetString("RegisteredHeadNodeIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headnode name in registry is null.
        /// </summary>
        internal static string RegisteredHeadNodeIsNull {
            get {
                return ResourceManager.GetString("RegisteredHeadNodeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]: Environment variable CCP_SERVICE_CONFIG_FILENAME is undefined.
        /// </summary>
        internal static string ServiceConfigFileNameNotSpecified {
            get {
                return ResourceManager.GetString("ServiceConfigFileNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker shut down this service host when shrinking session&apos;s resource allocation..
        /// </summary>
        internal static string ServiceShutdownFromBrokerShrink {
            get {
                return ResourceManager.GetString("ServiceShutdownFromBrokerShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service host is canceled or preempted..
        /// </summary>
        internal static string TaskCanceledOrPreempted {
            get {
                return ResourceManager.GetString("TaskCanceledOrPreempted", resourceCulture);
            }
        }
    }
}
