//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ComputeCluster.Test.AppIntegration.EchoService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatisticInfo", Namespace="http://schemas.datacontract.org/2004/07/EchoSvcLib")]
    public partial class StatisticInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime endTimeField;
        
        private System.DateTime startTimeField;
        
        private int taskIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int taskId
        {
            get
            {
                return this.taskIdField;
            }
            set
            {
                this.taskIdField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IEchoSvc")]
    public interface IEchoSvc
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEchoSvc/Echo", ReplyAction = "http://tempuri.org/IEchoSvc/EchoResponse")]
        string Echo(string input);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IEchoSvc/Echo", ReplyAction = "http://tempuri.org/IEchoSvc/EchoResponse")]
        System.IAsyncResult BeginEcho(string input, System.AsyncCallback callback, object asyncState);

        string EndEcho(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEchoSvc/GenerateLoad", ReplyAction = "http://tempuri.org/IEchoSvc/GenerateLoadResponse")]
        Microsoft.ComputeCluster.Test.AppIntegration.EchoService.StatisticInfo GenerateLoad(double runMilliSeconds, byte[] dummyData, string fileData);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IEchoSvc/GenerateLoad", ReplyAction = "http://tempuri.org/IEchoSvc/GenerateLoadResponse")]
        System.IAsyncResult BeginGenerateLoad(double runMilliSeconds, byte[] dummyData, string fileData, System.AsyncCallback callback, object asyncState);

        Microsoft.ComputeCluster.Test.AppIntegration.EchoService.StatisticInfo EndGenerateLoad(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IEchoSvc/EchoData", ReplyAction = "http://tempuri.org/IEchoSvc/EchoDataResponse")]
        int EchoData(string dataClientId);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IEchoSvc/EchoData", ReplyAction = "http://tempuri.org/IEchoSvc/EchoDataResponse")]
        System.IAsyncResult BeginEchoData(string dataClientId, System.AsyncCallback callback, object asyncState);

        int EndEchoData(System.IAsyncResult result);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IEchoSvcChannel : IEchoSvc, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EchoSvcClient : System.ServiceModel.ClientBase<IEchoSvc>, IEchoSvc
    {

        public EchoSvcClient()
        {
        }

        public EchoSvcClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public EchoSvcClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public EchoSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public EchoSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string Echo(string input)
        {
            return base.Channel.Echo(input);
        }

        public System.IAsyncResult BeginEcho(string input, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginEcho(input, callback, asyncState);
        }

        public string EndEcho(System.IAsyncResult result)
        {
            return base.Channel.EndEcho(result);
        }

        public Microsoft.ComputeCluster.Test.AppIntegration.EchoService.StatisticInfo GenerateLoad(double runMilliSeconds, byte[] dummyData, string fileData)
        {
            return base.Channel.GenerateLoad(runMilliSeconds, dummyData, fileData);
        }

        public System.IAsyncResult BeginGenerateLoad(double runMilliSeconds, byte[] dummyData, string fileData, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGenerateLoad(runMilliSeconds, dummyData, fileData, callback, asyncState);
        }

        public Microsoft.ComputeCluster.Test.AppIntegration.EchoService.StatisticInfo EndGenerateLoad(System.IAsyncResult result)
        {
            return base.Channel.EndGenerateLoad(result);
        }

        public int EchoData(string dataClientId)
        {
            return base.Channel.EchoData(dataClientId);
        }

        public System.IAsyncResult BeginEchoData(string dataClientId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginEchoData(dataClientId, callback, asyncState);
        }

        public int EndEchoData(System.IAsyncResult result)
        {
            return base.Channel.EndEchoData(result);
        }
    }

}


