//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Telepathy.ServiceBroker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Telepathy.ServiceBroker.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is not authorized to access the client {1}. Please make sure you are the owner of the client..
        /// </summary>
        internal static string AccessDenied_BrokerQueue {
            get {
                return ResourceManager.GetString("AccessDenied_BrokerQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authentication failure. User {0} is not authorized to use this session..
        /// </summary>
        internal static string AuthenticationFailure {
            get {
                return ResourceManager.GetString("AuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding {0} is not supported..
        /// </summary>
        internal static string BindingNotSupported {
            get {
                return ResourceManager.GetString("BindingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding security mode is not matched..
        /// </summary>
        internal static string BindingSecurityModeMismatched {
            get {
                return ResourceManager.GetString("BindingSecurityModeMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker failed to obtain Azure storage connection string of the cluster. Please check if it has been set for the cluster..
        /// </summary>
        internal static string Broker_AzureConnectionStringNotAvailable {
            get {
                return ResourceManager.GetString("Broker_AzureConnectionStringNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRequest must be called after sending some requests..
        /// </summary>
        internal static string Broker_EOMReject_NoRequest {
            get {
                return ResourceManager.GetString("Broker_EOMReject_NoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker is unavailable due to loss of heartbeat. Make sure you can connect to the broker node, the HpcBroker service is running on the broker node and the session is still running..
        /// </summary>
        internal static string BrokerIsUnavailable {
            get {
                return ResourceManager.GetString("BrokerIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read response message from broker queue.
        /// </summary>
        internal static string BrokerQueueFailure {
            get {
                return ResourceManager.GetString("BrokerQueueFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker is suspending and could not accept any incoming request..
        /// </summary>
        internal static string BrokerSuspending {
            get {
                return ResourceManager.GetString("BrokerSuspending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find custom binding in the configuration file..
        /// </summary>
        internal static string CannotFindCustomBindingConfiguration {
            get {
                return ResourceManager.GetString("CannotFindCustomBindingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client id: Client Id does not match the former messages on this channel.
        /// </summary>
        internal static string ClientIdNotMatch {
            get {
                return ResourceManager.GetString("ClientIdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client id: Client ID is too long. The maximum length is 128 characters..
        /// </summary>
        internal static string ClientIdTooLong {
            get {
                return ResourceManager.GetString("ClientIdTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is purged..
        /// </summary>
        internal static string ClientPurged {
            get {
                return ResourceManager.GetString("ClientPurged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is timed out. Please try again later..
        /// </summary>
        internal static string ClientTimeout {
            get {
                return ResourceManager.GetString("ClientTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the scheduler..
        /// </summary>
        internal static string ConnectionToSchedulerIsNotReady {
            get {
                return ResourceManager.GetString("ConnectionToSchedulerIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate EndRequests is called.
        /// </summary>
        internal static string DuplicateEndOfMessage {
            get {
                return ResourceManager.GetString("DuplicateEndOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRequests was already called for this BrokerClient..
        /// </summary>
        internal static string EOMReject_EndRequests {
            get {
                return ResourceManager.GetString("EOMReject_EndRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRequests was already called for this BrokerClient or the session&apos;s service job ended..
        /// </summary>
        internal static string EOMReject_GetResponse {
            get {
                return ResourceManager.GetString("EOMReject_GetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRequests is not allowed for this client, the client is now in the {0} state..
        /// </summary>
        internal static string EOMRejected {
            get {
                return ResourceManager.GetString("EOMRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get job property ids..
        /// </summary>
        internal static string FailedToGetJobPropertyId {
            get {
                return ResourceManager.GetString("FailedToGetJobPropertyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get job state..
        /// </summary>
        internal static string FailedToGetJobState {
            get {
                return ResourceManager.GetString("FailedToGetJobState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush() is not allowed for this client. The client is now in the &apos;{0}&apos; state..
        /// </summary>
        internal static string FlushRejected {
            get {
                return ResourceManager.GetString("FlushRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetResponses handler disposed.
        /// </summary>
        internal static string GetResponsesHandlerDisposed {
            get {
                return ResourceManager.GetString("GetResponsesHandlerDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure storage connection string is invalid..
        /// </summary>
        internal static string InvalidAzureStorageConnectionString {
            get {
                return ResourceManager.GetString("InvalidAzureStorageConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client id: Client id could only have these characters: 0-9, a-z, A-Z, _, -, {, } and space..
        /// </summary>
        internal static string InvalidClientId {
            get {
                return ResourceManager.GetString("InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client id: Client id could only have these characters: 0-9, a-z, A-Z, _, -, {, } and space and should not contains more than 128 characters..
        /// </summary>
        internal static string InvalidClientIdOrTooLong {
            get {
                return ResourceManager.GetString("InvalidClientIdOrTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load network prefix..
        /// </summary>
        internal static string LoadNetworkPrefixFailed {
            get {
                return ResourceManager.GetString("LoadNetworkPrefixFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure storage connection string is not set..
        /// </summary>
        internal static string MissAzureStorageConnectionString {
            get {
                return ResourceManager.GetString("MissAzureStorageConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default uri for scheme {0} could be found..
        /// </summary>
        internal static string NoDefaultUriForScheme {
            get {
                return ResourceManager.GetString("NoDefaultUriForScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport scheme {0} is not supported..
        /// </summary>
        internal static string NotSupportedTransportScheme {
            get {
                return ResourceManager.GetString("NotSupportedTransportScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open frontend: {0}..
        /// </summary>
        internal static string OpenFrontEndFailed {
            get {
                return ResourceManager.GetString("OpenFrontEndFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register job in session launcher: {0}..
        /// </summary>
        internal static string RegisterJobFailed {
            get {
                return ResourceManager.GetString("RegisterJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed {0} time(s) and is marked as failure by the broker. The exception is {1}..
        /// </summary>
        internal static string RetryLimitExceeded {
            get {
                return ResourceManager.GetString("RetryLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send back the response..
        /// </summary>
        internal static string SendBackResponseFailed {
            get {
                return ResourceManager.GetString("SendBackResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service job is failed or canceled..
        /// </summary>
        internal static string ServiceFailed {
            get {
                return ResourceManager.GetString("ServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: session {0} can not be attached due to its state..
        /// </summary>
        internal static string Session_ValidateJobFailed_AlreadyFninshed {
            get {
                return ResourceManager.GetString("Session_ValidateJobFailed_AlreadyFninshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session failed or Cancelled.
        /// </summary>
        internal static string SessionFailure {
            get {
                return ResourceManager.GetString("SessionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker storage is closed..
        /// </summary>
        internal static string StorageClosed {
            get {
                return ResourceManager.GetString("StorageClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker storage failed: {0}..
        /// </summary>
        internal static string StorageFailure {
            get {
                return ResourceManager.GetString("StorageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker storage service is not available..
        /// </summary>
        internal static string StorageServiceNotAvailble {
            get {
                return ResourceManager.GetString("StorageServiceNotAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker storage hits quota limit or is full. If you are using MSMQ, contact your administrator to increase MSMQ storage quota on broker node or clean up session storages manually. Please refer http://support.microsoft.com/kb/899612 to change the quota..
        /// </summary>
        internal static string StorageSpaceNotSufficient {
            get {
                return ResourceManager.GetString("StorageSpaceNotSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed because the corresponding task is in failed or canceled state..
        /// </summary>
        internal static string TaskFailed {
            get {
                return ResourceManager.GetString("TaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttling timeout exceeded..
        /// </summary>
        internal static string ThrottlingTimeoutExceeded {
            get {
                return ResourceManager.GetString("ThrottlingTimeoutExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured: {0}..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is not authorized to access the client {1}. Please make sure you are the owner of the client..
        /// </summary>
        internal static string UserNameNotMatch {
            get {
                return ResourceManager.GetString("UserNameNotMatch", resourceCulture);
            }
        }
    }
}
