//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Hpc.Scheduler.Session {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Hpc.Scheduler.Session.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the session&apos;s broker: Permission denied..
        /// </summary>
        internal static string AccessDenied_Broker {
            get {
                return ResourceManager.GetString("AccessDenied_Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the HpcBroker service: Permission denied..
        /// </summary>
        internal static string AccessDenied_BrokerLauncher {
            get {
                return ResourceManager.GetString("AccessDenied_BrokerLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the broker&apos;s storage: Permission denied..
        /// </summary>
        internal static string AccessDenied_BrokerQueue {
            get {
                return ResourceManager.GetString("AccessDenied_BrokerQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllocationAdjustInterval must be a positive number..
        /// </summary>
        internal static string AllocationAdjustIntervalPositive {
            get {
                return ResourceManager.GetString("AllocationAdjustIntervalPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A client has closed the session..
        /// </summary>
        internal static string AllTasksFinished {
            get {
                return ResourceManager.GetString("AllTasksFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same message type has been returned from different operations. Action parameter must be specified by the caller..
        /// </summary>
        internal static string AmbiguousOperation {
            get {
                return ResourceManager.GetString("AmbiguousOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be empty..
        /// </summary>
        internal static string ArgumentEmpty {
            get {
                return ResourceManager.GetString("ArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; cannot be an empty string..
        /// </summary>
        internal static string ArgumentEmptyString {
            get {
                return ResourceManager.GetString("ArgumentEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the related broker node for session {0}. One possible cause is that the session is still in the configuring stage. Retry later..
        /// </summary>
        internal static string AttachConfiguringSession {
            get {
                return ResourceManager.GetString("AttachConfiguringSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the broker node for the session {0}. The job {0} is not a session job..
        /// </summary>
        internal static string AttachNoBrokerSession {
            get {
                return ResourceManager.GetString("AttachNoBrokerSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed due to the incorrect username and/or password..
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to use this session..
        /// </summary>
        internal static string AuthenticationFailure {
            get {
                return ResourceManager.GetString("AuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DurableSession is not supported when the scheduler is in Azure..
        /// </summary>
        internal static string Azure_NotSupportDurableSession {
            get {
                return ResourceManager.GetString("Azure_NotSupportDurableSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backend session provider is not supported. The provider is derived from the specified argument..
        /// </summary>
        internal static string BackendNotSupported {
            get {
                return ResourceManager.GetString("BackendNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property is not implemented by backend session provider..
        /// </summary>
        internal static string BackendPropertyNotFound {
            get {
                return ResourceManager.GetString("BackendPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified binding does not match the specified TransportScheme..
        /// </summary>
        internal static string BindingTransportSchemeMismatch {
            get {
                return ResourceManager.GetString("BindingTransportSchemeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker has already been closed. This might be because that a previous call to close broker has timed out..
        /// </summary>
        internal static string Broker_AlreadyClosed {
            get {
                return ResourceManager.GetString("Broker_AlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker has already been initialized..
        /// </summary>
        internal static string Broker_AlreadyInitialized {
            get {
                return ResourceManager.GetString("Broker_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is not authorized to use this session..
        /// </summary>
        internal static string Broker_AuthenticationFailure {
            get {
                return ResourceManager.GetString("Broker_AuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding {0} is not supported..
        /// </summary>
        internal static string Broker_BindingNotSupported {
            get {
                return ResourceManager.GetString("Broker_BindingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security mode of the binding must match the Session.Secure property..
        /// </summary>
        internal static string Broker_BindingSecurityModeMismatched {
            get {
                return ResourceManager.GetString("Broker_BindingSecurityModeMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot attach to the session. The session {0} is in the Finishing state..
        /// </summary>
        internal static string Broker_BrokerFinishing {
            get {
                return ResourceManager.GetString("Broker_BrokerFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker node is offline and cannot accept requests to create or attach to a session..
        /// </summary>
        internal static string Broker_BrokerIsOffline {
            get {
                return ResourceManager.GetString("Broker_BrokerIsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read response messages from the broker&apos;s storage..
        /// </summary>
        internal static string Broker_BrokerQueueFailure {
            get {
                return ResourceManager.GetString("Broker_BrokerQueueFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker service failed to start..
        /// </summary>
        internal static string Broker_BrokerServiceFailedStartup {
            get {
                return ResourceManager.GetString("Broker_BrokerServiceFailedStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker is unavailable due to loss of heartbeat. Make sure you can connect to the broker node, the HpcBroker service is running on the broker node and the session is still running..
        /// </summary>
        internal static string Broker_BrokerUnavailable {
            get {
                return ResourceManager.GetString("Broker_BrokerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find custom binding in the service configuration file..
        /// </summary>
        internal static string Broker_CannotFindCustomBindingConfiguration {
            get {
                return ResourceManager.GetString("Broker_CannotFindCustomBindingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get job owner from the scheduler..
        /// </summary>
        internal static string Broker_CannotGetUserSID {
            get {
                return ResourceManager.GetString("Broker_CannotGetUserSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid clientId. ClientId does not match the corresponding messages on this connection..
        /// </summary>
        internal static string Broker_ClientIdNotMatch {
            get {
                return ResourceManager.GetString("Broker_ClientIdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the scheduler is not ready. It might be that the scheduler service or HpcSession service on the headnode is not started..
        /// </summary>
        internal static string Broker_ConnectionToSchedulerIsNotReady {
            get {
                return ResourceManager.GetString("Broker_ConnectionToSchedulerIsNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom broker exited unexpectedly. ExitCode = {0}..
        /// </summary>
        internal static string Broker_CustomBrokerExitBeforeReady {
            get {
                return ResourceManager.GetString("Broker_CustomBrokerExitBeforeReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred when starting the custom broker. Current timeout is {0}..
        /// </summary>
        internal static string Broker_CustomBrokerReadyTimeout {
            get {
                return ResourceManager.GetString("Broker_CustomBrokerReadyTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRequests was already called for this BrokerClient..
        /// </summary>
        internal static string Broker_EOMReject_EndRequests {
            get {
                return ResourceManager.GetString("Broker_EOMReject_EndRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRequests was already called for this BrokerClient or the session&apos;s service job ended..
        /// </summary>
        internal static string Broker_EOMReject_GetResponse {
            get {
                return ResourceManager.GetString("Broker_EOMReject_GetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRequests is not allowed. The client is in the {0} state..
        /// </summary>
        internal static string Broker_EOMRejected {
            get {
                return ResourceManager.GetString("Broker_EOMRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get job property Ids from the scheduler..
        /// </summary>
        internal static string Broker_FailedToGetJobPropertyId {
            get {
                return ResourceManager.GetString("Broker_FailedToGetJobPropertyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get job state from the scheduler..
        /// </summary>
        internal static string Broker_FailedToGetJobState {
            get {
                return ResourceManager.GetString("Broker_FailedToGetJobState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get job template security descriptor from the scheduler..
        /// </summary>
        internal static string Broker_FailedToGetSecurityDescriptor {
            get {
                return ResourceManager.GetString("Broker_FailedToGetSecurityDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start broker service process. Win32 error code: {0}..
        /// </summary>
        internal static string Broker_FailedToStartBrokerServiceProcess {
            get {
                return ResourceManager.GetString("Broker_FailedToStartBrokerServiceProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid clientId. ClientId can only have these characters: 0-9, a-z, A-Z, _, -, {, } and space and cannot contain more than 128 characters..
        /// </summary>
        internal static string Broker_InvalidClientIdOrTooLong {
            get {
                return ResourceManager.GetString("Broker_InvalidClientIdOrTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session id, {0}, is invalid..
        /// </summary>
        internal static string Broker_InvalidSessionId {
            get {
                return ResourceManager.GetString("Broker_InvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get network prefix from the service task environment variable WCF_NETWORKPREFIX..
        /// </summary>
        internal static string Broker_LoadNetworkPrefixFailed {
            get {
                return ResourceManager.GetString("Broker_LoadNetworkPrefixFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default uri for scheme {0} could be found..
        /// </summary>
        internal static string Broker_NoDefaultUriForScheme {
            get {
                return ResourceManager.GetString("Broker_NoDefaultUriForScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker has not been initialized..
        /// </summary>
        internal static string Broker_NotInitialized {
            get {
                return ResourceManager.GetString("Broker_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport scheme {0} is not supported..
        /// </summary>
        internal static string Broker_NotSupportedTransportScheme {
            get {
                return ResourceManager.GetString("Broker_NotSupportedTransportScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open frontend: {0}..
        /// </summary>
        internal static string Broker_OpenFrontEndFailed {
            get {
                return ResourceManager.GetString("Broker_OpenFrontEndFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get data from job properties from the job scheduler needed to restart the session..
        /// </summary>
        internal static string Broker_PullDataFromCustomJobPropertyFailed {
            get {
                return ResourceManager.GetString("Broker_PullDataFromCustomJobPropertyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register job in session service: {0}..
        /// </summary>
        internal static string Broker_RegisterJobFailed {
            get {
                return ResourceManager.GetString("Broker_RegisterJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed {0} time(s) and is marked as failed by the broker. The exception is {1}..
        /// </summary>
        internal static string Broker_RetryLimitExceeded {
            get {
                return ResourceManager.GetString("Broker_RetryLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send back the responses. Connection to the client is likely faulted..
        /// </summary>
        internal static string Broker_SendBackResponseFailed {
            get {
                return ResourceManager.GetString("Broker_SendBackResponseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service job is failed or canceled..
        /// </summary>
        internal static string Broker_ServiceFailed {
            get {
                return ResourceManager.GetString("Broker_ServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is failed or canceled. Please refer to the reason of the session&apos;s job for more information..
        /// </summary>
        internal static string Broker_SessionFailure {
            get {
                return ResourceManager.GetString("Broker_SessionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session {0} has already been created..
        /// </summary>
        internal static string Broker_SessionIdAlreadyExists {
            get {
                return ResourceManager.GetString("Broker_SessionIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active sessions running on this broker node has exceeded the limit - {0}. Increase maxConcurrentSession setting in HpcBroker.exe.config..
        /// </summary>
        internal static string Broker_TooManyBrokerRunning {
            get {
                return ResourceManager.GetString("Broker_TooManyBrokerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured: {0}..
        /// </summary>
        internal static string Broker_UnknownError {
            get {
                return ResourceManager.GetString("Broker_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &quot;{0}&quot; is not supported by current broker. Please consider upgrading your broker node..
        /// </summary>
        internal static string Broker_UnsupportedOperation {
            get {
                return ResourceManager.GetString("Broker_UnsupportedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session was originally created by a broker whose version is not supported by current broker. Please consider upgrading your broker node..
        /// </summary>
        internal static string Broker_UnsupportedVersion {
            get {
                return ResourceManager.GetString("Broker_UnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is not authorized to access the BrokerClient with an clientId of {1}..
        /// </summary>
        internal static string Broker_UserNameNotMatch {
            get {
                return ResourceManager.GetString("Broker_UserNameNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested transport scheme is not supported by broker client..
        /// </summary>
        internal static string BrokerClientTransportSchemeNotSupport {
            get {
                return ResourceManager.GetString("BrokerClientTransportSchemeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker is unavailable due to loss of heartbeat. Make sure you can connect to the broker node, the HpcBroker service is running on the broker node and the session is still running..
        /// </summary>
        internal static string BrokerIsUnavailable {
            get {
                return ResourceManager.GetString("BrokerIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker node is unavailable due to loss of heartbeat. Make sure you can connect to the broker node and the HpcBroker service is running on the broker node..
        /// </summary>
        internal static string BrokerNodeIsUnavailable {
            get {
                return ResourceManager.GetString("BrokerNodeIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the session information of session {0}..
        /// </summary>
        internal static string CannotGetSessionInfo {
            get {
                return ResourceManager.GetString("CannotGetSessionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a certificate to upload to the scheduler.
        /// </summary>
        internal static string CertificateChooser_Text {
            get {
                return ResourceManager.GetString("CertificateChooser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a SOA client certificate for Azure cluster.
        /// </summary>
        internal static string CertificateChooser_Text_Azure {
            get {
                return ResourceManager.GetString("CertificateChooser_Text_Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Chooser.
        /// </summary>
        internal static string CertificateChooser_Title {
            get {
                return ResourceManager.GetString("CertificateChooser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientBrokerHeartbeatInterval must be a positive number..
        /// </summary>
        internal static string ClientBrokerHeartbeatIntervalPositive {
            get {
                return ResourceManager.GetString("ClientBrokerHeartbeatIntervalPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientBrokerHeartbeatRetryCount must be a positive number..
        /// </summary>
        internal static string ClientBrokerHeartbeatRetryCountPositive {
            get {
                return ResourceManager.GetString("ClientBrokerHeartbeatRetryCountPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientIdleTimeout must be a positive number..
        /// </summary>
        internal static string ClientIdleTimeoutNotNegative {
            get {
                return ResourceManager.GetString("ClientIdleTimeoutNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId is too long. The maximum length is 128 characters..
        /// </summary>
        internal static string ClientIdTooLong {
            get {
                return ResourceManager.GetString("ClientIdTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BrokerClient has been purged. No more responses may be received..
        /// </summary>
        internal static string ClientPurged {
            get {
                return ResourceManager.GetString("ClientPurged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BrokerClient has timed out. Retry later..
        /// </summary>
        internal static string ClientTimeout {
            get {
                return ResourceManager.GetString("ClientTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout occurred when creating session. The broker {0} did not respond in {1} milliseconds. Make sure HPC Broker Service is running on broker node..
        /// </summary>
        internal static string ConectBrokerLauncherTimeout {
            get {
                return ResourceManager.GetString("ConectBrokerLauncherTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file is invalid: {0}..
        /// </summary>
        internal static string ConfigFile_Invalid {
            get {
                return ResourceManager.GetString("ConfigFile_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to HPC broker service. See inner exception for details..
        /// </summary>
        internal static string ConnectBrokerLauncherFailure {
            get {
                return ResourceManager.GetString("ConnectBrokerLauncherFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to data service..
        /// </summary>
        internal static string ConnectDataServiceFailure {
            get {
                return ResourceManager.GetString("ConnectDataServiceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred when connecting to data service..
        /// </summary>
        internal static string ConnectDataServiceTimeout {
            get {
                return ResourceManager.GetString("ConnectDataServiceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to HPC session service. See inner exception for details..
        /// </summary>
        internal static string ConnectSessionLauncherFailure {
            get {
                return ResourceManager.GetString("ConnectSessionLauncherFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred when creating the session. Scheduler did not respond in {0} milliseconds. Retry later..
        /// </summary>
        internal static string ConnectSessionLauncherTimeout {
            get {
                return ResourceManager.GetString("ConnectSessionLauncherTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HpcSession service does not have a connection to the scheduler yet. Scheduler service may not be started or is busy. Retry later..
        /// </summary>
        internal static string ConnectToSchedulerFailure {
            get {
                return ResourceManager.GetString("ConnectToSchedulerFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a session or attach to a session on Windows HPC Server 2008..
        /// </summary>
        internal static string ConnectToV2Cluster {
            get {
                return ResourceManager.GetString("ConnectToV2Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create job: {0}..
        /// </summary>
        internal static string CreateJobFailure {
            get {
                return ResourceManager.GetString("CreateJobFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set job properties. The scheduler raised exception: {0}..
        /// </summary>
        internal static string CreateJobPropertiesFailure {
            get {
                return ResourceManager.GetString("CreateJobPropertiesFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create task. The scheduler raised exception: {0}..
        /// </summary>
        internal static string CreateJobTasksFailure {
            get {
                return ResourceManager.GetString("CreateJobTasksFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create session procedure has been canceled by user..
        /// </summary>
        internal static string CreateSessionCanceled {
            get {
                return ResourceManager.GetString("CreateSessionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CredentialTypeDialog_CancelButtonString {
            get {
                return ResourceManager.GetString("CredentialTypeDialog_CancelButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a &amp;softcard certificate.
        /// </summary>
        internal static string CredentialTypeDialog_CertCheckBoxString {
            get {
                return ResourceManager.GetString("CredentialTypeDialog_CertCheckBoxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an authentication method.
        /// </summary>
        internal static string CredentialTypeDialog_LabelString {
            get {
                return ResourceManager.GetString("CredentialTypeDialog_LabelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string CredentialTypeDialog_OkButtonString {
            get {
                return ResourceManager.GetString("CredentialTypeDialog_OkButtonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a &amp;username/password.
        /// </summary>
        internal static string CredentialTypeDialog_PwdCheckBoxString {
            get {
                return ResourceManager.GetString("CredentialTypeDialog_PwdCheckBoxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataClient &apos;{0}&apos; already exists..
        /// </summary>
        internal static string DataClientAlreadyExists {
            get {
                return ResourceManager.GetString("DataClientAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open DataClient &apos;{0}&apos; because it is being created. Please retry later..
        /// </summary>
        internal static string DataClientBeingCreated {
            get {
                return ResourceManager.GetString("DataClientBeingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform the operation because DataClient &apos;{0}&apos; is used by someone else. Please retry later..
        /// </summary>
        internal static string DataClientBusy {
            get {
                return ResourceManager.GetString("DataClientBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform the operation because DataClient &apos;{0}&apos; is deleted..
        /// </summary>
        internal static string DataClientDeleted {
            get {
                return ResourceManager.GetString("DataClientDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access a disposed DataClient instance..
        /// </summary>
        internal static string DataClientDisposed {
            get {
                return ResourceManager.GetString("DataClientDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DataClient ID. A DataClient ID can only have the following characters: 0-9, a-z, A-Z, _, -, {, } and a space. And it cannot be ended with a space..
        /// </summary>
        internal static string DataClientIdInvalid {
            get {
                return ResourceManager.GetString("DataClientIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataClient ID is too long. The maximum length is {0} characters..
        /// </summary>
        internal static string DataClientIdTooLong {
            get {
                return ResourceManager.GetString("DataClientIdTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataClient &apos;{0}&apos; is already associated with a life cycle object..
        /// </summary>
        internal static string DataClientLifeCycleSet {
            get {
                return ResourceManager.GetString("DataClientLifeCycleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataClient &apos;{0}&apos; is not found..
        /// </summary>
        internal static string DataClientNotFound {
            get {
                return ResourceManager.GetString("DataClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add data to DataClient &apos;{0}&apos; because WriteAll&lt;T&gt; or WriteRawBytesAll has been called on it..
        /// </summary>
        internal static string DataClientNotWritable {
            get {
                return ResourceManager.GetString("DataClientNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform the operation. DataClient instance obtained via open operation is read only and can not be modified..
        /// </summary>
        internal static string DataClientReadOnly {
            get {
                return ResourceManager.GetString("DataClientReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOA data feature is not supported by SOA session service. Please contact your HPC system administrator..
        /// </summary>
        internal static string DataFeatureNotSupported {
            get {
                return ResourceManager.GetString("DataFeatureNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform the operation on DataClient &apos;{0}&apos; because it is in inconsistent state. This is usually caused by unexpected application or system crash. Please delete the DataClient if this error occurs repeatedly..
        /// </summary>
        internal static string DataInconsistent {
            get {
                return ResourceManager.GetString("DataInconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum data size {0} is exceeded..
        /// </summary>
        internal static string DataMaxSizeExceeded {
            get {
                return ResourceManager.GetString("DataMaxSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. No permission to perform the operation..
        /// </summary>
        internal static string DataNoPermission {
            get {
                return ResourceManager.GetString("DataNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform the operation. Please retry later..
        /// </summary>
        internal static string DataRetry {
            get {
                return ResourceManager.GetString("DataRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad data server address {0}. Please contact your HPC system administrator..
        /// </summary>
        internal static string DataServerBadAddress {
            get {
                return ResourceManager.GetString("DataServerBadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data server for Azure burst is not configured properly. Please contact your HPC system administrator..
        /// </summary>
        internal static string DataServerForAzureBurstMisconfigured {
            get {
                return ResourceManager.GetString("DataServerForAzureBurstMisconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data server {0} is not configured properly. Please contact your HPC system administrator..
        /// </summary>
        internal static string DataServerMisconfigured {
            get {
                return ResourceManager.GetString("DataServerMisconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data server is out of space..
        /// </summary>
        internal static string DataServerNoSpace {
            get {
                return ResourceManager.GetString("DataServerNoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data server type {0}. Please consider upgrading your HPC client library..
        /// </summary>
        internal static string DataServerNotSupported {
            get {
                return ResourceManager.GetString("DataServerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reach data server at {0}. Please contact your HPC system administrator..
        /// </summary>
        internal static string DataServerUnreachable {
            get {
                return ResourceManager.GetString("DataServerUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to transfer data to Azure storage. Inner exception: {0}..
        /// </summary>
        internal static string DataTransferToAzureFailed {
            get {
                return ResourceManager.GetString("DataTransferToAzureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert data to from type &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string DataTypeMismatch {
            get {
                return ResourceManager.GetString("DataTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string DataUnknownError {
            get {
                return ResourceManager.GetString("DataUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read data of version {0}. Current version is {1}..
        /// </summary>
        internal static string DataVersionNotSupported {
            get {
                return ResourceManager.GetString("DataVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent sessions are not supported in DEBUG mode..
        /// </summary>
        internal static string DebugModeNotSupportConcurrentSession {
            get {
                return ResourceManager.GetString("DebugModeNotSupportConcurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified task id {0} is not valid. Check your task id and try again..
        /// </summary>
        internal static string DiagService_InvalidTaskId {
            get {
                return ResourceManager.GetString("DiagService_InvalidTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DispatcherCapacityInGrowShrink must be a non-negative value..
        /// </summary>
        internal static string DispatcherCapacityInGrowShrinkNonNegative {
            get {
                return ResourceManager.GetString("DispatcherCapacityInGrowShrinkNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified clientId is already being used with this Session..
        /// </summary>
        internal static string DuplicateClientId {
            get {
                return ResourceManager.GetString("DuplicateClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a valid endpoint reference from the HpcBroker service..
        /// </summary>
        internal static string EndpointAddressNotValid {
            get {
                return ResourceManager.GetString("EndpointAddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndpointNotFoundRetryCountLimit must be a non-negative number..
        /// </summary>
        internal static string EndpointNotFoundRetryCountLimitNotNegative {
            get {
                return ResourceManager.GetString("EndpointNotFoundRetryCountLimitNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session&apos;s jobs have been started but the corresponding broker has not. Retry later..
        /// </summary>
        internal static string EndpointTimeout {
            get {
                return ResourceManager.GetString("EndpointTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred when submitting the job, see the inner exception for details..
        /// </summary>
        internal static string ExceptionInCreatingSession {
            get {
                return ResourceManager.GetString("ExceptionInCreatingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get cluster property. The scheduler raised exception: {0}..
        /// </summary>
        internal static string GetClusterPropertyFailure {
            get {
                return ResourceManager.GetString("GetClusterPropertyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve data server information from session launcher..
        /// </summary>
        internal static string GetDataServerInfoFailure {
            get {
                return ResourceManager.GetString("GetDataServerInfoFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get job property. The scheduler raised exception: {0}..
        /// </summary>
        internal static string GetJobPropertyFailure {
            get {
                return ResourceManager.GetString("GetJobPropertyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter headnode cannot be null or an empty string..
        /// </summary>
        internal static string HeadNodeCannotBeNullOfEmpty {
            get {
                return ResourceManager.GetString("HeadNodeCannotBeNullOfEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The headnode cannot be null or empty. Please check the headnode parameter and environment variables..
        /// </summary>
        internal static string HeadnodeCantBeNull {
            get {
                return ResourceManager.GetString("HeadnodeCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified backend property type is it incorrect. It is expected to be of type {0}..
        /// </summary>
        internal static string IncorrectBackendPropertyType {
            get {
                return ResourceManager.GetString("IncorrectBackendPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session {0} does not exist in the current process. It might be because you are trying to attach to an inprocess broker which exists in another process, or the given session id is invalid..
        /// </summary>
        internal static string InprocessBroker_InvalidSessionId {
            get {
                return ResourceManager.GetString("InprocessBroker_InvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durable sessions are not supported in inprocess broker scenario..
        /// </summary>
        internal static string InprocessBroker_NotSupportDurableSession {
            get {
                return ResourceManager.GetString("InprocessBroker_NotSupportDurableSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session pool is not supported in inprocess broker scenario..
        /// </summary>
        internal static string InprocessBroker_NotSupportSessionPool {
            get {
                return ResourceManager.GetString("InprocessBroker_NotSupportSessionPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared sessions are not supported in inprocess broker scenario..
        /// </summary>
        internal static string InprocessBroker_NotSupportShareSession {
            get {
                return ResourceManager.GetString("InprocessBroker_NotSupportShareSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent sessions are not supported in inprocess broker scenario..
        /// </summary>
        internal static string InprocessNotSupportConcurrentSession {
            get {
                return ResourceManager.GetString("InprocessNotSupportConcurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} cannot be mapped to a known identity..
        /// </summary>
        internal static string InvalidAllowedUser {
            get {
                return ResourceManager.GetString("InvalidAllowedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndpointPrefix: {0} is not supported, please pass in &quot;net.tcp://&quot; or &quot;https://&quot;..
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot attach to a durable session using the Session.Attach method. Use the DurableSession.Attach method instead..
        /// </summary>
        internal static string InvalidAttachDurableSession {
            get {
                return ResourceManager.GetString("InvalidAttachDurableSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot attach to an interactive session using the DurableSession.Attach method. Use the Session.Attach method instead..
        /// </summary>
        internal static string InvalidAttachInteractiveSession {
            get {
                return ResourceManager.GetString("InvalidAttachInteractiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid clientId. A BrokerClient clientId can only have the following characters: 0-9, a-z, A-Z, _, -, {, } and a space..
        /// </summary>
        internal static string InvalidClientId {
            get {
                return ResourceManager.GetString("InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data provider configuration setting: downloadBlobMaxBackoffInSeconds value must be equal or greater than downloadBlobMinBackoffInSeconds..
        /// </summary>
        internal static string InvalidDownloadBlobMaxBackoff {
            get {
                return ResourceManager.GetString("InvalidDownloadBlobMaxBackoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data provider configuration setting: downloadBlobMinBackoffInSeconds value must be a positive number..
        /// </summary>
        internal static string InvalidDownloadBlobMinBackoff {
            get {
                return ResourceManager.GetString("InvalidDownloadBlobMinBackoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data provider configuration setting: downloadBlobRetryCount value must be equal or greater than 0..
        /// </summary>
        internal static string InvalidDownloadBlobRetryCount {
            get {
                return ResourceManager.GetString("InvalidDownloadBlobRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data provider configuration setting: downloadBlobThreadCount value must be a positive number..
        /// </summary>
        internal static string InvalidDownloadBlobThreadCount {
            get {
                return ResourceManager.GetString("InvalidDownloadBlobThreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data provider configuration setting: downloadBlobTimeoutInSeconds value must be greater than 0..
        /// </summary>
        internal static string InvalidDownloadBlobTimeout {
            get {
                return ResourceManager.GetString("InvalidDownloadBlobTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndpointNotFoundRetryPeriod must be a positive number..
        /// </summary>
        internal static string InvalidEndpointNotFoundRetryPeriod {
            get {
                return ResourceManager.GetString("InvalidEndpointNotFoundRetryPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendRequest must be called at least once before EndRequests..
        /// </summary>
        internal static string InvalidEndRequestsCount {
            get {
                return ResourceManager.GetString("InvalidEndRequestsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data provider configuration setting: fileShareBufferSizeInKiloBytes value must be a positive number..
        /// </summary>
        internal static string InvalidFileShareBufferSize {
            get {
                return ResourceManager.GetString("InvalidFileShareBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of FileShare data server: {0}. This value should be a single UNC path. Please contact your HPC system administrator..
        /// </summary>
        internal static string InvalidFileShareFormat {
            get {
                return ResourceManager.GetString("InvalidFileShareFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxConnectionCountPerAzureProxy must be a positive number..
        /// </summary>
        internal static string InvalidMaxConnectionCountPerAzureProxy {
            get {
                return ResourceManager.GetString("InvalidMaxConnectionCountPerAzureProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageID of the incoming message is invalid. It must be an instance of UniqueId which contains a GUID..
        /// </summary>
        internal static string InvalidMessageId {
            get {
                return ResourceManager.GetString("InvalidMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceOperationTimeout must be a positive number..
        /// </summary>
        internal static string InvalidServiceOperationTimeout {
            get {
                return ResourceManager.GetString("InvalidServiceOperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceRequestPrefetchCount must be a non-negative number..
        /// </summary>
        internal static string InvalidServiceRequestPrefetchCount {
            get {
                return ResourceManager.GetString("InvalidServiceRequestPrefetchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service version string was returned from HpcSession service..
        /// </summary>
        internal static string InvalidServiceVersionReturned {
            get {
                return ResourceManager.GetString("InvalidServiceVersionReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session type. The session must be of type Session or DurableSession..
        /// </summary>
        internal static string InvalidSessionType {
            get {
                return ResourceManager.GetString("InvalidSessionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout can be only positive, 0 or -1. -1 is infinite..
        /// </summary>
        internal static string InvalidTimeout {
            get {
                return ResourceManager.GetString("InvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transport scheme..
        /// </summary>
        internal static string InvalidTransportScheme {
            get {
                return ResourceManager.GetString("InvalidTransportScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find broker load balancing configuration section in service&apos;s configuration file..
        /// </summary>
        internal static string LoadBalancingConfigurationMissing {
            get {
                return ResourceManager.GetString("LoadBalancingConfigurationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadSamplingInterval must be a positive number..
        /// </summary>
        internal static string LoadSamplingIntervalPositive {
            get {
                return ResourceManager.GetString("LoadSamplingIntervalPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Broker Mode only supports NetTcp binding..
        /// </summary>
        internal static string LocalBrokerOnlySupportNetTcp {
            get {
                return ResourceManager.GetString("LocalBrokerOnlySupportNetTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Broker Mode only supports non-shared session..
        /// </summary>
        internal static string LocalBrokerOnlySupportNonShared {
            get {
                return ResourceManager.GetString("LocalBrokerOnlySupportNonShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageRetryLimit must be a non-negative number..
        /// </summary>
        internal static string MessageRetryLimitNotNegative {
            get {
                return ResourceManager.GetString("MessageRetryLimitNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageThrottleStartThreshold must be greater than MessageThrottleStopThreshold..
        /// </summary>
        internal static string MessageThrottleStartGreaterStop {
            get {
                return ResourceManager.GetString("MessageThrottleStartGreaterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageThrottleStopThreshold cannot be less than 0..
        /// </summary>
        internal static string MessageThrottleStopThresholdPositive {
            get {
                return ResourceManager.GetString("MessageThrottleStopThresholdPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find broker monitor configuration section in service&apos;s configuration file..
        /// </summary>
        internal static string MonitorConfigurationMissing {
            get {
                return ResourceManager.GetString("MonitorConfigurationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default binding for Custom transport scheme can be loaded. Use alternative constructor BrokerClient(SessionBase, Binding) to indicate binding information instead..
        /// </summary>
        internal static string MustIndicateBindingForCustomTransportScheme {
            get {
                return ResourceManager.GetString("MustIndicateBindingForCustomTransportScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportScheme must be indicated to a value (NetTcp, Http or Custom)..
        /// </summary>
        internal static string MustIndicateTransportScheme {
            get {
                return ResourceManager.GetString("MustIndicateTransportScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a broker node in the cluster that meets the session&apos;s requirements. Please check the documentation on how to configure a broker node. If you are using failover broker nodes and creating a DurableSession, please be sure one or more failover broker nodes are online..
        /// </summary>
        internal static string NoBrokerNodeFound {
            get {
                return ResourceManager.GetString("NoBrokerNodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP_HOME environment variable is not set..
        /// </summary>
        internal static string NoCCPHOMEENV {
            get {
                return ResourceManager.GetString("NoCCPHOMEENV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataClient &apos;{0}&apos; contains no data..
        /// </summary>
        internal static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data server is configured..
        /// </summary>
        internal static string NoDataServerConfigured {
            get {
                return ResourceManager.GetString("NoDataServerConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durable Session does not support Http binding..
        /// </summary>
        internal static string NotAllowHttpTransport {
            get {
                return ResourceManager.GetString("NotAllowHttpTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AsyncResult object..
        /// </summary>
        internal static string NotCorrectAsyncResultObj {
            get {
                return ResourceManager.GetString("NotCorrectAsyncResultObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A BrokerClient object can only have one response handler or active GetResponses enumerator at a time..
        /// </summary>
        internal static string OneResponseEnumerationPerBrokerClient {
            get {
                return ResourceManager.GetString("OneResponseEnumerationPerBrokerClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open job: {0}..
        /// </summary>
        internal static string OpenJobFailure {
            get {
                return ResourceManager.GetString("OpenJobFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occured. Retry later or increase specified timeout..
        /// </summary>
        internal static string OperationTimeout {
            get {
                return ResourceManager.GetString("OperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The retry failure count exceeded. The request was marked as failed by the broker. Check the exception&apos;s Reason property for details..
        /// </summary>
        internal static string RetryOperationExceptionMessage {
            get {
                return ResourceManager.GetString("RetryOperationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TransportScheme..
        /// </summary>
        internal static string SchemaNotValid {
            get {
                return ResourceManager.GetString("SchemaNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send timeout must be positive..
        /// </summary>
        internal static string SendTimeoutMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("SendTimeoutMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service configuration file is not found. Make sure configuration file for service {0} is deployed to the %CCP_SERVICEREGISTRATION_PATH%..
        /// </summary>
        internal static string Service_NotFound {
            get {
                return ResourceManager.GetString("Service_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service registration directories are specified in CCP_SERVICEREGISTRATION_PATH..
        /// </summary>
        internal static string Service_RegistrationDirsMissing {
            get {
                return ResourceManager.GetString("Service_RegistrationDirsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceContext is not available. ServiceContext is only available within the HpcServiceHost.exe..
        /// </summary>
        internal static string ServiceContextIsNotAvailable {
            get {
                return ResourceManager.GetString("ServiceContextIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service name cannot be null or empty. It can only contain &quot;0-9&quot;, &quot;a-z&quot;, &quot;A-Z&quot;, &quot;.&quot;, &quot;-&quot; and &quot;_&quot;, and less than 255 characters..
        /// </summary>
        internal static string ServiceNameCantBeNull {
            get {
                return ResourceManager.GetString("ServiceNameCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP_SERVICEREGISTRATION_PATH could not be found in the cluster configuration environments..
        /// </summary>
        internal static string ServiceRegistrationPathEnvironmentMissing {
            get {
                return ResourceManager.GetString("ServiceRegistrationPathEnvironmentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find broker services configuration section in service&apos;s configuration file..
        /// </summary>
        internal static string ServicesConfigurationMissing {
            get {
                return ResourceManager.GetString("ServicesConfigurationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service version not found. Please make sure service {0}_{1} is deployed to the %CCP_SERVICEREGISTRATION_PATH%..
        /// </summary>
        internal static string ServiceVersion_NotFound {
            get {
                return ResourceManager.GetString("ServiceVersion_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service version should not be 0 for both major and minor versions..
        /// </summary>
        internal static string ServiceVersionNoZeroMajorAndMinor {
            get {
                return ResourceManager.GetString("ServiceVersionNoZeroMajorAndMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: session {0} cannot be attached to because the session has already finished..
        /// </summary>
        internal static string Session_ValidateJobFailed_AlreadyFninshed {
            get {
                return ResourceManager.GetString("Session_ValidateJobFailed_AlreadyFninshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: session {0} cannot be attached to when the service job is canceled..
        /// </summary>
        internal static string Session_ValidateJobFailed_JobCanceled {
            get {
                return ResourceManager.GetString("Session_ValidateJobFailed_JobCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: session {0} is an interactive session. It can only be attached to when its service job is queued or running..
        /// </summary>
        internal static string Session_ValidateJobFailed_NotDurableSession {
            get {
                return ResourceManager.GetString("Session_ValidateJobFailed_NotDurableSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach session failed: job {0} is not a service job..
        /// </summary>
        internal static string Session_ValidateJobFailed_NotServiceJob {
            get {
                return ResourceManager.GetString("Session_ValidateJobFailed_NotServiceJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job cannot be canceled because it is in Configuring or Validating state. Try again later..
        /// </summary>
        internal static string SessionCannotBeCanceled {
            get {
                return ResourceManager.GetString("SessionCannotBeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session ID &apos;{0}&apos;..
        /// </summary>
        internal static string SessionIdInvalid {
            get {
                return ResourceManager.GetString("SessionIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionIdleTimeout must be a positive number..
        /// </summary>
        internal static string SessionIdleTimeoutNotNegative {
            get {
                return ResourceManager.GetString("SessionIdleTimeoutNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get SSDL for broker node {0}. Inner exception: {1}.
        /// </summary>
        internal static string SessionLauncher_FailedToGetBrokerNodeSSDL {
            get {
                return ResourceManager.GetString("SessionLauncher_FailedToGetBrokerNodeSSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the endpoint for the HPC session service on node {0}. The headnode name may be incorrect, the HPC session service may not be started on the specified headnode or the client may be using an unsupported feature with a previous version of HPC Server..
        /// </summary>
        internal static string SessionLauncherEndpointNotFound {
            get {
                return ResourceManager.GetString("SessionLauncherEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOA client certificate for Azure cluster is not specified. Either choose one in the certificate selection dialog, or set the certificate thumbprint to env var CCP_SOACLIENTCERT_THUMBPRINT..
        /// </summary>
        internal static string SoaClientCertNotSpecified {
            get {
                return ResourceManager.GetString("SoaClientCertNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportScheme.Http with false Secure is not supported. Please check the session start info settings. .
        /// </summary>
        internal static string StartInfo_HttpBindingWithSecure {
            get {
                return ResourceManager.GetString("StartInfo_HttpBindingWithSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusUpdateInterval must be a positive number..
        /// </summary>
        internal static string StatusUpdateIntervalPositive {
            get {
                return ResourceManager.GetString("StatusUpdateIntervalPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker storage is closed..
        /// </summary>
        internal static string StorageClosed {
            get {
                return ResourceManager.GetString("StorageClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker storage failed: {0}..
        /// </summary>
        internal static string StorageFailure {
            get {
                return ResourceManager.GetString("StorageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker storage service is not available..
        /// </summary>
        internal static string StorageServiceNotAvailble {
            get {
                return ResourceManager.GetString("StorageServiceNotAvailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The broker&apos;s storage has hit its quota limit or is full. Ask your administrator to increase MSMQ storage quota on the broker node or clean up durable sessions manually via DurableSession.Close(true). Refer http://support.microsoft.com/kb/899612 to change the MSMQ quota..
        /// </summary>
        internal static string StorageSpaceNotSufficient {
            get {
                return ResourceManager.GetString("StorageSpaceNotSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit job: {0}.
        /// </summary>
        internal static string SubmitJobFailure {
            get {
                return ResourceManager.GetString("SubmitJobFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred while waiting for responses. Timeout = {0} ms..
        /// </summary>
        internal static string TimeoutGetResponse {
            get {
                return ResourceManager.GetString("TimeoutGetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get broker worker process within 1 minute. Broker node is busy. Retry later..
        /// </summary>
        internal static string TimeoutToGetBrokerWorkerProcess {
            get {
                return ResourceManager.GetString("TimeoutToGetBrokerWorkerProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested transport scheme is not supported by a durable session..
        /// </summary>
        internal static string TransportSchemeNotSupport {
            get {
                return ResourceManager.GetString("TransportSchemeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportScheme.WebAPI is exclusive and is not designed to be used with other options at the same time..
        /// </summary>
        internal static string TransportSchemeWebAPIExclusive {
            get {
                return ResourceManager.GetString("TransportSchemeWebAPIExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UnitType property requires that the value be defined as a JobUnitType enumeration..
        /// </summary>
        internal static string UnitTypeNotDefined {
            get {
                return ResourceManager.GetString("UnitTypeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured: {0}..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session pool is not supported by unshared session..
        /// </summary>
        internal static string UnsharedSession_NotSupportSessionPool {
            get {
                return ResourceManager.GetString("UnsharedSession_NotSupportSessionPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserData can only be {0} characters. Specified userData length is {1} characters..
        /// </summary>
        internal static string UserDataTooLong {
            get {
                return ResourceManager.GetString("UserDataTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string WebAPI_AccessDenied {
            get {
                return ResourceManager.GetString("WebAPI_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker of session {0} is not active. This maybe because the session has suspended or finished (because of timeout). Try to attach to the session first..
        /// </summary>
        internal static string WebAPI_BrokerNotActive {
            get {
                return ResourceManager.GetString("WebAPI_BrokerNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session API does not support to cancel session creation when creating a session over a Web service..
        /// </summary>
        internal static string WebAPI_NotSupportCancelCreateSession {
            get {
                return ResourceManager.GetString("WebAPI_NotSupportCancelCreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inprocess broker is not supported through Web API. Please use Session API directly for this feature..
        /// </summary>
        internal static string WebAPI_NotSupportInprocessBroker {
            get {
                return ResourceManager.GetString("WebAPI_NotSupportInprocessBroker", resourceCulture);
            }
        }
    }
}
