//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Hpc.Azure.FileStaging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Hpc.Azure.FileStaging.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node {0} has not been mapped to a physical node..
        /// </summary>
        internal static string Azure_MissingNodeMapping {
            get {
                return ResourceManager.GetString("Azure_MissingNodeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error forwarding the request to node {0}: {1}..
        /// </summary>
        internal static string Common_CantForward {
            get {
                return ResourceManager.GetString("Common_CantForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to communicate with the intermediate blob storage..
        /// </summary>
        internal static string Common_IntermediateBlobStorageCommunicationFailure {
            get {
                return ResourceManager.GetString("Common_IntermediateBlobStorageCommunicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate storage account is not configured properly. Please contact your cluster administrators..
        /// </summary>
        internal static string Common_IntermediateBlobStorageMisConfigured {
            get {
                return ResourceManager.GetString("Common_IntermediateBlobStorageMisConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error. If this keeps occuring, please contact your cluster administrators..
        /// </summary>
        internal static string Common_InternalServerError {
            get {
                return ResourceManager.GetString("Common_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request does not contain the required header &apos;{0}&apos;..
        /// </summary>
        internal static string Common_MissingHeaders {
            get {
                return ResourceManager.GetString("Common_MissingHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target file {0} already exists..
        /// </summary>
        internal static string Common_TargetFileExists {
            get {
                return ResourceManager.GetString("Common_TargetFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the credentials string..
        /// </summary>
        internal static string OnPremise_CantParseCredentials {
            get {
                return ResourceManager.GetString("OnPremise_CantParseCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create channel to proxy. The head node address is not known..
        /// </summary>
        internal static string OnPremise_HeadNodeUnknown {
            get {
                return ResourceManager.GetString("OnPremise_HeadNodeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t impersonate the user &quot;{0}&quot;. Reason: {1}.
        /// </summary>
        internal static string OnPremise_ImpersonationFailure {
            get {
                return ResourceManager.GetString("OnPremise_ImpersonationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows security API call {0} failed. GetLastError returned {1}..
        /// </summary>
        internal static string OnPremise_InteropFailed {
            get {
                return ResourceManager.GetString("OnPremise_InteropFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot distinguish between multiple Windows Azure nodes with that name..
        /// </summary>
        internal static string OnPremise_MultipleMatches {
            get {
                return ResourceManager.GetString("OnPremise_MultipleMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only cluster administrators or users are allowed to access cluster files..
        /// </summary>
        internal static string OnPremise_OnlyClusterUsersAllowed {
            get {
                return ResourceManager.GetString("OnPremise_OnlyClusterUsersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the head node may call the file staging service..
        /// </summary>
        internal static string OnPremise_OnlyHeadNodeAllowed {
            get {
                return ResourceManager.GetString("OnPremise_OnlyHeadNodeAllowed", resourceCulture);
            }
        }
    }
}
